CREATE TABLE players (player_id NUMBER PRIMARY KEY,
					player_number NUMBER(2) UNIQUE,
					position varchar2(50),
					first_name varchar2(50),
					last_name varchar2(50),
					birth_date DATE,
					nationality varchar2(50),
					height_cm number(3),
					preferred_foot varchar2(10) CHECK (preferred_foot IN ('left','right','both')),
					joined_club DATE,
					contract_until DATE);