INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 50, 'Goalkeeper', 'Slawomir', 'Abramowicz', TO_DATE('09-06-2004', 'DD-MM-YYYY'), 'Poland', 189, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 22, 'Goalkeeper', 'Milosz', 'Piekutowski', TO_DATE('08-05-2006', 'DD-MM-YYYY'), 'Poland', 189, 'both');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 33, 'Goalkeeper', 'Bartlomiej', 'Zynel', TO_DATE('09-04-1998', 'DD-MM-YYYY'), 'Poland', 187, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 13, 'Centre-back', 'Bernardo', 'Vital', TO_DATE('29-12-2000', 'DD-MM-YYYY'), 'Portugal', 187, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 17, 'Centre-back', 'Adrián', 'Diéguez', TO_DATE('04-02-1996', 'DD-MM-YYYY'), 'Spain', 188, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 3, 'Centre-back', 'Dusan', 'Stojinovic', TO_DATE('26-08-2000', 'DD-MM-YYYY'), 'Slovenia', 187, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 4, 'Centre-back', 'Yuki', 'Kobayashi', TO_DATE('18-07-2000', 'DD-MM-YYYY'), 'Japan', 185, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 27, 'Left-Back', 'Bartlomiej', 'Wdowik', TO_DATE('25-09-2000', 'DD-MM-YYYY'), 'Poland', 184, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 5, 'Left-Back', 'Cezary', 'Polak', TO_DATE('31-05-2003', 'DD-MM-YYYY'), 'Poland', 185, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 15, 'Right-Back', 'Norbert', 'Wojtuszek', TO_DATE('05-10-2001', 'DD-MM-YYYY'), 'Poland', 184, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 82, 'Right-Back', 'Tomás', 'Silva', TO_DATE('15-10-1999', 'DD-MM-YYYY'), 'Portugal', 172, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 31, 'Defensive Midfield', 'Leon', 'Flach', TO_DATE('28-02-2001', 'DD-MM-YYYY'), 'United States', 183, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 6, 'Defensive Midfield', 'Taras', 'Romanczuk', TO_DATE('14-11-1991', 'DD-MM-YYYY'), 'Poland', 186, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 85, 'Defensive Midfield', 'Eryk', 'Kozlowski', TO_DATE('27-09-2006', 'DD-MM-YYYY'), 'Poland', 181, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 29, 'Defensive Midfield', 'Marcin', 'Listkowski', TO_DATE('10-02-1998', 'DD-MM-YYYY'), 'Poland', 178, 'both');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 8, 'Attacking Midfield', 'Dawid', 'Drachal', TO_DATE('31-01-2005', 'DD-MM-YYYY'), 'Poland', 182, 'both');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 11, 'Attacking Midfield', 'Jesús', 'Imaz', TO_DATE('26-09-1990', 'DD-MM-YYYY'), 'Spain', 174, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 86, 'Attacking Midfield', 'Bartosz', 'Mazurek', TO_DATE('03-01-2007', 'DD-MM-YYYY'), 'Poland', 176, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 80, 'Left winger', 'Oskar', 'Pietuszewski', TO_DATE('20-05-2008', 'DD-MM-YYYY'), 'Poland', 179, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 19, 'Left winger', 'Álex', 'Cantero', TO_DATE('08-06-2000', 'DD-MM-YYYY'), 'Spain', 184, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 18, 'Right winger', 'Louka', 'Prip', TO_DATE('29-06-1997', 'DD-MM-YYYY'), 'Denmark', 182, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 20, 'Right winger', 'Miki', 'Villar', TO_DATE('19-09-1996', 'DD-MM-YYYY'), 'Spain', 173, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 10, 'Centre-forward', 'Afimico', 'Pululu', TO_DATE('23-03-1999', 'DD-MM-YYYY'), 'DR Congo', 175, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 26, 'Centre-forward', 'Dimitris', 'Rallis', TO_DATE('26-03-2005', 'DD-MM-YYYY'), 'Greece', 189, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 25, 'Attacking Midfield', 'AZ', 'Jackson', TO_DATE('25-10-2001', 'DD-MM-YYYY'), 'United States', 175, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 17, 'Centre-Forward', 'Youssuf', 'Sylla', TO_DATE('19-12-2002', 'DD-MM-YYYY'), 'Belgium', 191, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 21, 'Central Midfield', 'Sergio', 'Lozano', TO_DATE('24-03-1999', 'DD-MM-YYYY'), 'Spain', 175, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 70, 'Centre-back', 'Andy', 'Pelmard', TO_DATE('12-03-2000', 'DD-MM-YYYY'), 'Madagascar', 181, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 72, 'Left winger', 'Kamil', 'Jozwiak', TO_DATE('22-04-1998', 'DD-MM-YYYY'), 'Poland', 176, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 72, 'Centre-back', 'Mateusz', 'Skrzypczak', TO_DATE('22-08-2000', 'DD-MM-YYYY'), 'Poland', 191, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 9, 'Centre-Forward', 'Lamine', 'Diaby-Fadiga', TO_DATE('19-01-2001', 'DD-MM-YYYY'), 'France', 188, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 16, 'Right-Back', 'Michal', 'Sacek', TO_DATE('19-09-1996', 'DD-MM-YYYY'), 'Czech Republic', 180, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 14, 'Defensive Midfield', 'Jarosław', 'Kubicki', TO_DATE('07-08-1995', 'DD-MM-YYYY'), 'Poland', 180, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 19, 'Right-Back', 'Paweł', 'Olszewski', TO_DATE('07-06-1999', 'DD-MM-YYYY'), 'Poland', 178, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 87, 'Centre-back', 'Dimitrios', 'Retsos', TO_DATE('07-08-2004', 'DD-MM-YYYY'), 'Greece', 188, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 99, 'Left winger', 'Kristoffer', 'Hansen', TO_DATE('12-08-1994', 'DD-MM-YYYY'), 'Norway', 180, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 23, 'Centre-back', 'Enzo', 'Ebosse', TO_DATE('11-03-1999', 'DD-MM-YYYY'), 'Cameroon', 185, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 44, 'Left-Back', 'João', 'Moutinho', TO_DATE('12-01-1998', 'DD-MM-YYYY'), 'Portugal', 183, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 21, 'Left winger', 'Darko', 'Churlinov', TO_DATE('11-07-2000', 'DD-MM-YYYY'), 'North Macedonia', 180, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 7, 'Right winger', 'Edi', 'Semedo', TO_DATE('01-06-1999', 'DD-MM-YYYY'), 'Cape Verde', 181, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 51, 'Centre-Forward', 'Alan', 'Rybak', TO_DATE('01-12-2006', 'DD-MM-YYYY'), 'Poland', 185, 'both');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 71, 'Defensive Midfield', 'Szymon', 'Stypułkowski', TO_DATE('17-03-2006', 'DD-MM-YYYY'), 'Poland', 182, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 1, 'Goalkeeper', 'Maksymilian', 'Stryjek', TO_DATE('18-07-1996', 'DD-MM-YYYY'), 'Poland', 188, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 7, 'Right-Back', 'Alex', 'Pozo', TO_DATE('22-02-1999', 'DD-MM-YYYY'), 'Spain', 172, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 23, 'Left-Back', 'Guilherme', 'Montóia', TO_DATE('14-09-2003', 'DD-MM-YYYY'), 'Portugal', 185, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 66, 'Goalkeeper', 'Adrian', 'Damasiewicz', TO_DATE('09-09-2008', 'DD-MM-YYYY'), 'Poland', 191, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 44, 'Centre-back', 'Apostolos', 'Konstantopoulos', TO_DATE('02-08-2002', 'DD-MM-YYYY'), 'Greece', 188, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 80, 'Right winger', 'Zachary', 'Zalewski', TO_DATE('03-01-2009', 'DD-MM-YYYY'), 'Poland', 170, 'left');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 19, 'Left winger', 'Matías', 'Nahuel', TO_DATE('22-11-1996', 'DD-MM-YYYY'), 'Spain', 172, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 77, 'Left winger', 'Kajetan', 'Szmyt', TO_DATE('29-05-2002', 'DD-MM-YYYY'), 'Poland', 171, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 14, 'Centre-Forward', 'Samed', 'Bazdar', TO_DATE('31-01-2004', 'DD-MM-YYYY'), 'Bosnia-Herzegovina', 189, 'right');
INSERT INTO football_db.players VALUES(player_seq.NEXTVAL, 90, 'Right winger', 'Maciej', 'Kuczyński', TO_DATE('01-02-2007', 'DD-MM-YYYY'), 'Poland', 193, 'both');
