INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Lech Poznan', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Rakow Czestochowa', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Polonia Warszawa', 'Poland', 'Betclic 1. Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Asteras Tripolis B', 'Greece', 'Super League 2');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Udinese', 'Italy', 'Serie A');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Spezia', 'Italy', 'Serie B');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Burnley', 'England', 'Premier League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Aris Limassol', 'Cyprus', 'Cypriot First Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Pogon Siedlce', 'Poland', 'Betclic 1. Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Kilmarnock FC', 'Scotland', 'Scottish Premiership');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Gornik Leczna', 'Poland', 'I liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Teplice', 'Czech Rep.', 'Czech First League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'KS Wasilkow', 'Poland', 'III liga (fourth tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Novi Pazar', 'Serbia', 'Serbian SuperLiga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Widzew Lodz', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Zaglebie Lubin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Legia Warszawa', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Lechia Gdansk', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Cracovia', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Arka Gdynia', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'GKS Katowice', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Korona Kielce', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Motor Lublin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Piast Gliwice', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Pogon Szczecin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Radomiak Radom', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Wisla Plock', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Bruk-Bet Termalica Nieciecza', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Gornik Zabrze', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Stal Stalowa Wola', 'Poland', 'II liga (third tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Heerenveen', 'Netherlands', 'Eredivisie');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'SC Braga', 'Portugal', 'Primeira Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Konyaspor', 'Turkey', 'Süper Lig');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Real Zaragoza', 'Spain', 'Segunda División');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Portimonense', 'Portugal', 'Primeira Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'UD Almeria', 'Spain', 'Segunda División');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CD Tenerife', 'Spain', 'Segunda División');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Columbus Crew', 'United States', 'Major League Soccer');
