INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Lech Poznan', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Rakow Czestochowa', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Polonia Warszawa', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Asteras Tripolis B', 'Greece', 'Super League 2');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Udinese', 'Italy', 'Serie A');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Spezia', 'Italy', 'Serie B');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Burnley', 'England', 'Premier League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Aris Limassol', 'Cyprus', 'Cypriot First Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Pogon Siedlce', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Kilmarnock FC', 'Scotland', 'Scottish Premiership');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Gornik Leczna', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Teplice', 'Czech Rep.', 'Czech First League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'KS Wasilkow', 'Poland', 'III liga (fourth tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Novi Pazar', 'Serbia', 'Serbian SuperLiga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Widzew Lodz', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Zaglebie Lubin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Legia Warszawa', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Lechia Gdansk', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Cracovia', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Arka Gdynia', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'GKS Katowice', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Korona Kielce', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Motor Lublin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Piast Gliwice', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Pogon Szczecin', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Radomiak Radom', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Wisla Plock', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Bruk-Bet Termalica Nieciecza', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Gornik Zabrze', 'Poland', 'PKO Bank Polski Ekstraklasa');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Stal Stalowa Wola', 'Poland', 'II liga (third tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Heerenveen', 'Netherlands', 'Eredivisie');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'SC Braga', 'Portugal', 'Primeira Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Konyaspor', 'Turkey', 'Süper Lig');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Real Zaragoza', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Portimonense', 'Portugal', 'Primeira Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'UD Almeria', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CD Tenerife', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Columbus Crew', 'United States', 'Major League Soccer');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Silkeborg IF', 'Denmark', 'Superligaen');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Royal Charleroi SC', 'Belgium', 'Jupiler Pro League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Granada CF', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Clermont Foot 63', 'France', 'Ligue 2');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Levante UD', 'Spain', 'Primera Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Wieczysta Krakow', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FC Dinamo City', 'Albania', 'Kategoria Superiore');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Dobrudzha Dobrich', 'Bulgaria', 'efbet Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Thep Xanh Nam Dinh FC ', 'Vietnam', 'V.League 1');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Hamrun Spartans', 'Malta', 'YoHealth Premier League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'RC Strasbourg', 'France', 'Ligue 1');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Miedz Legnica', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Skendija 79 (Tetovo)', 'North Macedonia', 'Macedonian First Football League');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Pogon Grodzisk Mazowiecki', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Kuopion Palloseura', 'Finland', 'Veikkausliiga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Rayo Vallecano de Madrid', 'Spain', 'Primera Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'AZ (Alkmaar)', 'Netherlands', 'Eredivisie')
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'GKS Tychy', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'SD Huesca', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Hvidovre IF', 'Denmark', '1.Division (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Vancouver Whitecaps FC', 'United States', 'Major League Soccer');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Maccabi Haifa', 'Israel', q'[Ligat ha'Al]');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CF Estrela Amadora ', 'Portugal', 'Liga Portugal ');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Linzer ASK', 'Austria', 'Bundesliga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CSKA 1948 Sofia', 'Bulgaria', 'efbet Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Cukaricki', 'Serbia', 'Serbian SuperLiga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'ACF Fiorentina', 'Italy', 'Serie A');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FC Porto ', 'Portugal', 'Liga Portugal ');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'GKS Tychy', 'Poland', 'Betclic 1. Liga (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'SD Huesca', 'Spain', 'Segunda Division');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Hvidovre IF', 'Denmark', '1.Division (second tier)');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Vancouver Whitecaps FC', 'United States', 'Major League Soccer');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Maccabi Haifa', 'Israel', q'[Ligat ha'Al]');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CF Estrela Amadora ', 'Portugal', 'Liga Portugal ');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'Linzer ASK', 'Austria', 'Bundesliga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'CSKA 1948 Sofia', 'Bulgaria', 'efbet Liga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FK Cukaricki', 'Serbia', 'Serbian SuperLiga');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'ACF Fiorentina', 'Italy', 'Serie A');
INSERT INTO clubs VALUES(club_seq.NEXTVAL, 'FC Porto ', 'Portugal', 'Liga Portugal ');
